#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

sparky_key=$(ynh_string_random --length=32 | base64)
ynh_app_setting_set --key=sparky_key --value=$sparky_key

secret_key=$(ynh_string_random --length=32 | base64)
ynh_app_setting_set --key=secret_key --value=$secret_key

disable_signup="false"
ynh_app_setting_set --key=disable_signup --value="$disable_signup"

openai_key=""
ynh_app_setting_set --key=openai_key --value=
googleai_key=""
ynh_app_setting_set --key=googleai_key --value=
anthropic_key=""
ynh_app_setting_set --key=anthropic_key --value=

db_name_seconduser="${db_name}_seconduser"
ynh_app_setting_set --key=db_name_seconduser --value=$db_name_seconduser

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

chown -R "$app:www-data" "$install_dir"

#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# PREPARE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring the PostgreSQL database..."

#Create postgis extension
ynh_psql_db_shell <<< "ALTER USER $db_user WITH SUPERUSER;"
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"
ynh_psql_db_shell <<< "ALTER USER $db_user WITH NOSUPERUSER;"

#=================================================
# PROVISION SECOND DB
#=================================================

ynh_script_progression "Configuring second PosqreSQL database..."
ynh_psql_create_db "$db_name_seconduser" "$db_user" "$db_pwd"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir/SparkyFitnessServer
	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

pushd $install_dir/SparkyFitnessFrontend
	ynh_hide_warnings ynh_exec_as_app npm install vite
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

pushd $install_dir/SparkyFitnessGarmin
	ynh_exec_as_app python3 -m venv "$install_dir/SparkyFitnessGarmin/venv"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/SparkyFitnessGarmin/venv/bin/pip" install --upgrade pip
	ynh_hide_warnings ynh_exec_as_app "$install_dir/SparkyFitnessGarmin/venv/bin/pip" install --no-cache-dir -r requirements.txt
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/.npm
ynh_safe_rm "$install_dir"/docker
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/SparkyFitnessMobile
ynh_safe_rm "$install_dir"/SparkyFitnessFrontend/node_modules

chown -R "$app:www-data" "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-garmin" --template="sparkyfitness-garmin.service"

yunohost service add "$app" --description=""$app"’s service" --log="/var/log/$app/$app.log"
yunohost service add "${app}-garmin" --description="Garmin integration for $app" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate
touch /var/log/$app/$app.log
touch /var/log/$app/${app}-garmin.log
chown -R $app:$app /var/log/$app/

# Create a dedicated Fail2Ban config
#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="${app}-garmin" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
