#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

openai_key=""
ynh_app_setting_set --key=openai_key --value=

googleai_key=""
ynh_app_setting_set --key=googleai_key --value=

anthropic_key=""
ynh_app_setting_set --key=anthropic_key --value=

sparky_key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=sparky_key --value=$sparky_key

secret_key=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=secret_key --value=$secret_key

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#chown -R "$app:www-data" "$install_dir"

#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir/SparkyFitnessServer
	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev
    ynh_hide_warnings ynh_exec_as_app npm run migrate

	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

pushd $install_dir
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add "$app" --description=""$app"’s service" --log="/var/log/$app/$app.log"

ynh_config_add_logrotate

# Create a dedicated Fail2Ban config
#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
