#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

#ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-garmin" >/dev/null; then
    yunohost service remove "$app-garmin"
fi
ynh_config_remove_systemd "${app}-garmin"

ynh_config_remove_nginx

#=================================================
# DROP TOKENSERVER DB
#=================================================
ynh_script_progression "Deprovisioning Seconduser DB..."

second_db_name=$(ynh_app_setting_get --key=second_db_name)
second_db_user=$(ynh_app_setting_get --key=second_db_user)

ynh_psql_drop_db "$second_db_name"
ynh_psql_drop_db "$second_db_user"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
