#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

#ynh_config_remove_fail2ban

ynh_config_remove_logrotate

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    yunohost service remove "$app"
fi
ynh_config_remove_systemd

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app-garmin" >/dev/null; then
    yunohost service remove "$app-garmin"
fi
ynh_config_remove_systemd "${app}-garmin"

ynh_config_remove_nginx

#=================================================
# DROP TOKENSERVER DB
#=================================================
ynh_script_progression --message="Deprovisioning Seconduser DB..."
db_name_seconduser=$(ynh_app_setting_get --key=db_name_seconduser)

ynh_psql_drop_db "$db_name_seconduser"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
