#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-garmin" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"


if ynh_app_upgrading_from_version_before 0.15.9.2~ynh1; then
	ynh_script_progression "Configuring second PosqreSQL database..."
	db_name_seconduser="${db_name}_seconduser"
	ynh_app_setting_set --key=db_name_seconduser --value=$db_name_seconduser
	ynh_psql_create_db "$db_name_seconduser" "$db_user" "$db_pwd"
fi

#=================================================
# PREPARE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring the PostgreSQL database..."

#Create postgis extension
ynh_psql_db_shell <<< "ALTER USER $db_user WITH SUPERUSER;"
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"
ynh_psql_db_shell <<< "ALTER USER $db_user WITH NOSUPERUSER;"

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir/SparkyFitnessServer
	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev
    ynh_hide_warnings ynh_exec_as_app npm run migrate
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

pushd $install_dir/SparkyFitnessFrontend
	ynh_hide_warnings ynh_exec_as_app npm install vite
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

pushd $install_dir/SparkyFitnessGarmin
	ynh_exec_as_app python3 -m venv "$install_dir/SparkyFitnessGarmin/venv"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/SparkyFitnessGarmin/venv/bin/pip" install --upgrade pip
	ynh_hide_warnings ynh_exec_as_app "$install_dir/SparkyFitnessGarmin/venv/bin/pip" install --no-cache-dir -r requirements.txt
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/.npm
ynh_safe_rm "$install_dir"/docker
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/SparkyFitnessMobile
ynh_safe_rm "$install_dir"/SparkyFitnessFrontend/node_modules

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-garmin" --template="sparkyfitness-garmin.service"

yunohost service add "$app" --description=""$app"’s service" --log="/var/log/$app/$app.log"
yunohost service add "${app}-garmin" --description="Garmin integration for $app" --log="/var/log/$app/$app-garmin.log"

ynh_config_add_logrotate
touch /var/log/$app/$app.log
touch /var/log/$app/${app}-garmin.log
chown -R $app:$app /var/log/$app/

#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="${app}-garmin" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
