#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

admin=$(ynh_user_get_info --username=$admin --key=username)
admin_mail=$(ynh_user_get_info --username=$admin --key=mail)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service="$app" --action="stop"
ynh_systemctl --service="$app-garmin" --action="stop"
ynh_systemctl --service="$app-mcp" --action="stop"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_setup_source --dest_dir="$install_dir" --full_replace

chown -R "$app:www-data" "$install_dir"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

chmod 400 "$install_dir/.env"
chown "$app:$app" "$install_dir/.env"

#=================================================
# PREPARE A POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Configuring the PostgreSQL database..."

#Create postgis extension
ynh_psql_db_shell <<< "ALTER USER $db_user WITH SUPERUSER;"
ynh_psql_db_shell <<< "ALTER USER $db_user CREATEROLE;"
ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS pg_stat_statements;"
ynh_psql_db_shell <<< "GRANT EXECUTE ON FUNCTION pg_stat_statements_reset TO $db_user;"
ynh_psql_db_shell <<< "ALTER USER $db_user WITH NOSUPERUSER;"

#=================================================
# CREATE AN ADDITIONAL DATABASE
#=================================================

if ynh_app_upgrading_from_version_before 0.16.4.9~ynh2
then
	db_name_seconduser=$(ynh_app_setting_get --key=db_name_seconduser)
	ynh_psql_drop_db "$db_name_seconduser"

	second_db_user=${app}_second
	second_db_name=$second_db_user
	second_db_pwd=$(ynh_string_random)

	ynh_psql_create_user "$second_db_user" "$second_db_pwd"
	ynh_psql_create_db "$second_db_name" "$second_db_user"
	ynh_app_setting_set --key=second_db_user --value=$second_db_user
	ynh_app_setting_set --key=second_db_name --value=$second_db_name
	ynh_app_setting_set --key=second_db_pwd --value=$second_db_pwd

fi


#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd $install_dir/SparkyFitnessServer
	ynh_hide_warnings ynh_exec_as_app npm ci --omit=dev

	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

pushd $install_dir/SparkyFitnessMCP
	ynh_hide_warnings npm install -g typescript
	ynh_hide_warnings npm install @types/node --save-dev
	ynh_hide_warnings ynh_exec_as_app npm run build
	ynh_hide_warnings ynh_exec_as_app npm cache clean --force
popd

pushd $install_dir/SparkyFitnessFrontend
	ynh_hide_warnings corepack enable && corepack prepare pnpm@10 --activate
	ynh_hide_warnings ynh_exec_as_app npm install vite
	ynh_hide_warnings ynh_exec_as_app npm run build
popd

pushd $install_dir/SparkyFitnessGarmin
	ynh_exec_as_app python3 -m venv "$install_dir/SparkyFitnessGarmin/venv"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/SparkyFitnessGarmin/venv/bin/pip" install --upgrade pip
	ynh_hide_warnings ynh_exec_as_app "$install_dir/SparkyFitnessGarmin/venv/bin/pip" install --no-cache-dir -r requirements.txt
popd

#Remove unneeded files
ynh_safe_rm "$install_dir"/.npm
ynh_safe_rm "$install_dir"/docker
ynh_safe_rm "$install_dir"/.github
ynh_safe_rm "$install_dir"/SparkyFitnessMobile
ynh_safe_rm "$install_dir"/SparkyFitnessFrontend/node_modules

chown -R "$app:www-data" "$install_dir"

#=================================================
# REAPPLY SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd
ynh_config_add_systemd --service="${app}-garmin" --template="sparkyfitness-garmin.service"
ynh_config_add_systemd --service="${app}-mcp" --template="sparkyfitness-mcp.service"

yunohost service add "$app" --description=""$app"’s service" --log="/var/log/$app/$app.log"
yunohost service add "${app}-garmin" --description="Garmin integration for $app" --log="/var/log/$app/$app-garmin.log"
yunohost service add "${app}-mcp" --description="$app MCP" --log="/var/log/$app/$app-mcp.log"

ynh_config_add_logrotate
touch /var/log/$app/$app.log
touch /var/log/$app/${app}-garmin.log
touch /var/log/$app/${app}-mcp.log
chown -R $app:$app /var/log/$app/


#ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service="$app" --action="start"
ynh_systemctl --service="${app}-garmin" --action="start"
ynh_systemctl --service="${app}-mcp" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
